<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { categories, normalizeService, posts, services } from './data/demo'
import { request } from './services/api'
import HomePage from './pages/HomePage.vue'
import ResourcesPage from './pages/ResourcesPage.vue'
import ResourceDetailPage from './pages/ResourceDetailPage.vue'
import CommunityPage from './pages/CommunityPage.vue'
import BookingPage from './pages/BookingPage.vue'
import AdminPage from './pages/AdminPage.vue'
import AssistantWorkspace from './components/assistant/AssistantWorkspace.vue'
const route=ref(location.hash.slice(1)||'/'), serviceList=ref(services), postList=ref(posts), selected=ref(null), activeCategory=ref('all'), homeOpened=ref(sessionStorage.getItem('wudong:scroll-opened')==='1'), joinedServiceIds=ref([]), orders=ref([]), adminTab=ref('orders')
const booking=ref({date:'',people:2,contact:'',phone:''}), pendingBooking=ref(null), bookingDone=ref(false), bookingLoading=ref(false), bookingLoadError=ref(''), bookingActionError=ref(''), adminActionError=ref('')
const filteredServices=computed(()=>activeCategory.value==='all'?serviceList.value:serviceList.value.filter(item=>item.category===activeCategory.value));const isAdmin=computed(()=>route.value.startsWith('/admin'))
function go(path){location.hash=path}
async function onHash(){route.value=location.hash.slice(1)||'/';const match=route.value.match(/^\/resource\/([^/]+)$/);if(!match)return;const id=decodeURIComponent(match[1]);selected.value=null;const local=serviceList.value.find(item=>String(item.id)===id);if(local)selected.value=local;try{selected.value=normalizeService(await request('/api/services/'+encodeURIComponent(id)))}catch(_){}}
function categoryLabel(id){return categories.find(c=>c.id===id)?.label||'乌东体验'}
async function openServiceById(value){const id=typeof value==='string'?value:(typeof value?.id==='string'?value.id:'');if(!id.trim())return;const fallback=serviceList.value.find(item=>String(item.id)===id);if(!fallback)return;selected.value=fallback;go('/resource/'+id);try{selected.value=normalizeService(await request('/api/services/'+id))}catch(_){}}
function navigate(action){if(action?.category)activeCategory.value=action.category;go(action?.path||'/')}
function openBooking(item){if(!item)return;selected.value=item;pendingBooking.value=null;bookingDone.value=false;bookingLoading.value=false;bookingLoadError.value='';bookingActionError.value='';booking.value={date:'',people:1,contact:'',phone:''};go('/booking')}
async function bookService(payload){const id=typeof payload?.serviceId==='string'?payload.serviceId:'';const handoffId=typeof payload?.pendingBooking?.id==='string'?payload.pendingBooking.id:'';if(!id.trim())return;const item=serviceList.value.find(value=>String(value.id)===id);if(!item)return;openBooking(item);if(!handoffId.trim())return;bookingLoading.value=true;try{const full=await request('/api/bookings/'+handoffId);if(full?.id!==handoffId)throw new Error('booking_id_mismatch');const locked=normalizeBooking(full,payload.pendingBooking.demoData);locked.id=handoffId;pendingBooking.value=locked;booking.value={date:full.travelDate,people:full.peopleCount,contact:full.contactName,phone:full.contactPhone}}catch(_){bookingLoadError.value='无法读取这笔待确认预约，请返回后重试。'}finally{bookingLoading.value=false}}
function normalizeBooking(item,fallbackDemoData=true){return{id:typeof item?.id==='string'?item.id:'',serviceId:typeof item?.serviceId==='string'?item.serviceId:'',name:item?.serviceName||item?.name||'乌东体验',date:item?.travelDate||item?.date||'',people:Number(item?.peopleCount||item?.people||0),contact:item?.contactName||'',phone:item?.contactPhone||'',status:item?.status,demoData:item?.demoData??fallbackDemoData}}
function normalizePost(item={}){const fallback=posts.find(post=>String(post.id)===String(item.id))||{};return{...fallback,...item,id:String(item.id||fallback.id||''),cover:item.coverUrl||item.cover||fallback.cover||'',coverAlt:item.coverAlt||fallback.coverAlt||'乌东寨里分享配图暂缺',title:item.title||fallback.title||'',text:item.content||item.text||fallback.text||''}}
function joinService(id){id=String(id||'');if(id&&!joinedServiceIds.value.includes(id))joinedServiceIds.value.push(id)}
async function submitBooking(){if(!selected.value)return;const complete=booking.value.date&&Number(booking.value.people)>0&&booking.value.contact.trim()&&booking.value.phone.trim();if(!complete){bookingActionError.value='请完整填写日期、人数、联系人和电话。';return}bookingActionError.value='';try{const result=await request('/api/bookings',{method:'POST',body:JSON.stringify({serviceId:String(selected.value.id),travelDate:booking.value.date,peopleCount:booking.value.people,contactName:booking.value.contact,contactPhone:booking.value.phone})});pendingBooking.value=normalizeBooking(result,selected.value.demoData)}catch(_){bookingActionError.value='暂时无法创建预约，请稍后重试。'}}
async function confirmBooking(){if(!pendingBooking.value?.id)return;bookingActionError.value='';try{const result=await request('/api/bookings/'+pendingBooking.value.id+'/confirm',{method:'POST'});const item=normalizeBooking(result,pendingBooking.value.demoData);orders.value.unshift(item);pendingBooking.value=item;bookingDone.value=true}catch(_){bookingActionError.value='确认预约失败，请稍后重试。'}}
async function updateOrder(order){adminActionError.value='';const next=order.status==='CONFIRMED'?'PROCESSING':'COMPLETED';try{order.status=(await request('/api/admin/bookings/'+order.id+'/status',{method:'PATCH',body:JSON.stringify({status:next})})).status}catch(_){adminActionError.value='订单状态更新失败，请稍后重试。'}}
onMounted(async()=>{addEventListener('hashchange',onHash);try{serviceList.value=(await request('/api/services')).map(normalizeService)}catch(_){};try{postList.value=(await request('/api/posts')).map(normalizePost)}catch(_){};onHash()});onUnmounted(()=>removeEventListener('hashchange',onHash))
</script>
<template><div :class="{'admin-shell':isAdmin}"><template v-if="!isAdmin"><header v-if="route!=='/'||homeOpened" class="topbar"><a class="brand" href="#/">贵州乌东</a><nav><a href="#/resources">游乌东</a><a href="#/community">寨里</a><a href="#/assistant">乌东向导</a></nav><button @click="go('/admin')">运营后台</button></header><HomePage v-if="route==='/'" :services="serviceList" :categories="categories" @gate-change="homeOpened=$event" @navigate="navigate" @open-service="openServiceById"><template #assistant><AssistantWorkspace embedded :joined-service-ids="joinedServiceIds" @open-service="openServiceById" @join-service="joinService" @book-service="bookService"/></template></HomePage><ResourcesPage v-else-if="route==='/resources'" :services="filteredServices" :categories="categories" :active-category="activeCategory" @filter="activeCategory=$event" @open-service="openServiceById"/><ResourceDetailPage v-else-if="route.startsWith('/resource/')" :service="selected" :category-label="categoryLabel(selected?.category)" @book="openBooking"/><CommunityPage v-else-if="route==='/community'" :posts="postList"/><main v-else-if="route==='/assistant'" class="page"><AssistantWorkspace :joined-service-ids="joinedServiceIds" @open-service="openServiceById" @join-service="joinService" @book-service="bookService"/></main><BookingPage v-else-if="route==='/booking'" :service="selected" :booking="booking" :pending="pendingBooking" :done="bookingDone" :latest-order="orders[0]" :loading="bookingLoading" :load-error="bookingLoadError" :action-error="bookingActionError" @update-booking="booking=$event" @submit="submitBooking" @confirm="confirmBooking" @open-admin="go('/admin')"/></template><AdminPage v-else :tab="adminTab" :orders="orders" :services="serviceList" :action-error="adminActionError" @change-tab="adminTab=$event" @update-order="updateOrder" @return-home="go('/')"/></div></template>
