const { createPhases, normalizeCard, applyEvent, settlePhases } = require('../../utils/assistant')
const { demoAssistantCard } = require('../../utils/demo')
const stringId = value => typeof value === 'string' && value.trim() ? value : ''
Page({
  data:{input:'我想体验贵州乌东的苗族文化和茶旅',messages:[],phases:createPhases(),currentCard:null,previousCard:null,isBusy:false,mode:'live',requestSeq:0,sourcesOpen:false,previousOpen:false},
  onShow(){wx.setNavigationBarTitle({title:'乌东向导'});this.getTabBar()?.setData({selected:2});const s=getApp().globalData.assistantSession;this.setData({messages:s.messages||[],currentCard:s.currentCard||null,previousCard:s.previousCard||null})},
  onUnload(){this.close(getApp().globalData.assistantSession.activeSocket)},
  sync(extra={}){Object.assign(getApp().globalData.assistantSession,{messages:this.data.messages,currentCard:this.data.currentCard,previousCard:this.data.previousCard},extra)},
  close(socket){if(socket)socket.close()},current(seq,socket){return seq===this.data.requestSeq&&socket===getApp().globalData.assistantSession.activeSocket},
  accept(seq,socket,raw){if(!this.current(seq,socket))return;const card=normalizeCard(raw),key=JSON.stringify([card.type,card.title,card.summary,card.data]);const s=getApp().globalData.assistantSession;if(s.cardKey===key)return;s.cardKey=key;this.setData({previousCard:this.data.currentCard||this.data.previousCard,currentCard:card,sourcesOpen:false,previousOpen:false});this.sync({cardKey:key});},
  fail(seq,socket,message){if(!this.current(seq,socket))return;this.setData({currentCard:{type:'error',title:'乌东向导暂不可用',summary:message,data:{demoAvailable:true},sources:[]},isBusy:false,mode:'error',phases:settlePhases(this.data.phases,true)});this.sync({activeSocket:null});this.close(socket)},
  ask(){const text=this.data.input.trim();if(!text)return;const s=getApp().globalData.assistantSession,seq=this.data.requestSeq+1,old=s.activeSocket;this.setData({requestSeq:seq,isBusy:true,mode:'live',phases:createPhases()});this.close(old);const messages=[...this.data.messages,{role:'user',content:text}];this.setData({messages});this.sync({messages,activeSocket:null});const socket=wx.connectSocket({url:getApp().globalData.aiWsUrl});s.activeSocket=socket;socket.onOpen(()=>{if(this.current(seq,socket))socket.send({data:JSON.stringify({thread_id:s.threadId,user_text:text})})});socket.onMessage(({data})=>{let e;try{e=JSON.parse(data)}catch(_){return}if(!this.current(seq,socket))return this.close(socket);if(e.type==='task_started')this.setData({phases:createPhases()});if(['node_started','tool_finished'].includes(e.type))this.setData({phases:applyEvent(this.data.phases,e)});if(e.type==='card_ready')this.accept(seq,socket,e.card);if(e.type==='completed'){this.setData({isBusy:false,phases:settlePhases(this.data.phases,false)});this.sync({activeSocket:null});this.close(socket)}if(e.type==='failed')this.fail(seq,socket,e.message||'请稍后重试。')});socket.onError(()=>this.fail(seq,socket,'本机 AI 服务暂未准备好。'));socket.onClose(()=>{if(this.current(seq,socket)&&this.data.isBusy)this.fail(seq,socket,'连接已断开。')})},
  showDemo(){if(this.data.currentCard?.data?.demoAvailable!==true)return;const s=getApp().globalData.assistantSession;this.setData({requestSeq:this.data.requestSeq+1,isBusy:false,mode:'demo',phases:settlePhases(this.data.phases,false)});this.close(s.activeSocket);s.activeSocket=null;this.setData({previousCard:this.data.currentCard,currentCard:normalizeCard(demoAssistantCard)});this.sync()},
  change(e){this.setData({input:e.detail.value})},quick(e){this.setData({input:e.currentTarget.dataset.text});this.ask()},toggleSources(){this.setData({sourcesOpen:!this.data.sourcesOpen})},togglePrevious(){this.setData({previousOpen:!this.data.previousOpen})},openService(e){const id=stringId(e.currentTarget.dataset.serviceId);if(id)wx.navigateTo({url:`/pages/detail/detail?id=${encodeURIComponent(id)}`})},bookService(e){const id=stringId(e.currentTarget.dataset.serviceId),booking=this.data.currentCard?.data?.booking;if(!id)return;getApp().globalData.pendingBooking=stringId(booking?.id)&&stringId(booking?.serviceId)?booking:null;wx.navigateTo({url:`/pages/booking/booking?id=${encodeURIComponent(id)}`})}
})
